<ol>
    <?php foreach ($this->getItems() as $_item): ?>
        <?php
        $stockKey       = 'stock-2';
        switch( strtolower( $_item->getLabel() ) ) {
            case 'direct leverbaar':
                $stockKey   = 'stock-0';
                break;
            case 'snel leverbaar':
                $stockKey   = 'stock-1';
                break;
        }
        ?>
        <li>
            <?php if ($_item->getCount() > 0): ?>
                <a href="<?php echo ($_item->isSelected()) ? $_item->getRemoveUrl() : $_item->getUrl() ?>">
                    <input type="checkbox"<?php if ($_item->isSelected()): ?> checked="checked" <?php endif; ?>/>
                    <?php echo $_item->getLabel() ?>
                    <?php if ($this->shouldDisplayProductCount()): ?>
                        <span class="count">(<?php echo $_item->getCount() ?>)</span>
                    <?php endif; ?>
                </a>
            <?php else: ?>
                <span>
                    <?php echo $_item->getLabel(); ?>
                    <?php if ($this->shouldDisplayProductCount()): ?>
                        <span class="count">(<?php echo $_item->getCount() ?>)</span>
                    <?php endif; ?>
                </span>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>